# Smart Theatre local Mosquitto TLS config

listener 8883
allow_anonymous true

certfile C:/Users/k/Desktop/FOG & EDGE COMPUTING/Smart_Theatre_Project/certs/server.crt
keyfile C:/Users/k/Desktop/FOG & EDGE COMPUTING/Smart_Theatre_Project/certs/server.key
require_certificate false

tls_version tlsv1.2

persistence false
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
